### ISSUE TITLE
Per-milestone preview displaying NaNs

### ISSUE THREAD

**Issue by spengrah** [raid-guild/escrow#15]
The Register form is not feeding correct values to the per-milestone preview on the left. This occurred after entering the initial `total raid payment` value, and for both DAI and WETH. However, the correct values did get displayed after changing that value again.

![image](https://user-images.githubusercontent.com/13247381/103951921-1ee5e000-5105-11eb-8bec-3d60fe5b4a2a.png)

**Comment by manolingam** [comment]
Made this https://github.com/raid-guild/escrow/pull/16 PR that fixes the NaN issue.
