### ISSUE TITLE
wrap long descriptions more

### ISSUE THREAD

**Issue by scottrepreneur** [raid-guild/escrow#5]
Check the Aave raid from the Raid Central v2. The wrap is pushed to the window width.

<img width="1347" alt="Screen Shot 2020-10-05 at 9 17 47 AM" src="https://user-images.githubusercontent.com/1778380/95091130-ad545b00-06eb-11eb-8cf3-e8f355c30e5b.png">

**Comment by manolingam** [comment]
Resolved in https://github.com/raid-guild/escrow/pull/8
